import { beforeAll, afterAll, describe, expect, it } from "vitest";
import { createHash, generateKeyPairSync, sign, type Server } from "node:crypto";
import { createServer } from "node:http";
import { exportJWK, SignJWT, type JWK } from "jose";
import { canonicalize } from "../../src/canonical/jcs.js";
import { envelopeBytes, type SignedEnvelopeV1 } from "../../src/crypto/envelope.js";
import { verify, authorityDecision, type VerificationContext } from "../../src/verification/verifier.js";
import type { TrustedKeyRegistry } from "../../src/identity/registry.js";
import type { RevocationRegistry } from "../../src/revocation/registry.js";
import type { ReplayStore, ClaimResult } from "../../src/replay/store.js";
import type { AuthorizationSnapshot } from "../../src/authorization/resources.js";
import type { DelegationCredential } from "../../src/delegation/verification.js";

const NOW = Math.floor(Date.now() / 1000), SUBJECT = "repo:Mise-OS/MiseOS-Dev-ID-:ref:refs/heads/main", REPO = "Mise-OS/MiseOS-Dev-ID-", AUD = "https://miseos.dev", KEY_ID = "dev-id-test-key", RESOURCE = "repo:Mise-OS/MiseOS-Dev-ID-:artifact:v1";
let jwksServer: Server, jwksUrl: URL, oidcPrivateKey: ReturnType<typeof generateKeyPairSync>, oidcJwk: JWK, signingPrivateKey: ReturnType<typeof generateKeyPairSync>["privateKey"], signingPublicDer: string;
class Keys implements TrustedKeyRegistry { constructor(public status: "valid"|"revoked"|"suspended"|"unknown" = "valid", public owner = SUBJECT) {} async resolveKey(id: string) { if (id !== KEY_ID) return { status: "unknown" as const }; if (this.status !== "valid") return { status: this.status }; return { status: "valid" as const, key: { keyId: id, publicKey: signingPublicDer, algorithm: "Ed25519" as const, owner: this.owner, issuedAt: new Date(NOW * 1000).toISOString() } }; } }
class Rev implements RevocationRegistry { constructor(public status: "valid"|"revoked"|"unknown" = "valid") {} async check(_id: string) { return { status: this.status, checkedAt: new Date().toISOString(), reason: this.status === "revoked" ? "test revocation" : undefined }; } }
class Replay implements ReplayStore { constructor(public result: ClaimResult = "claimed") {} async claimNonce() { return this.result; } async hasNonce() { return this.result === "replayed"; } }
async function oidc(overrides: Record<string, unknown> = {}) { return new SignJWT({ sub: SUBJECT, iss: "https://token.actions.githubusercontent.com", aud: AUD, repository: REPO, repository_owner: "Mise-OS", repository_id: "1338747102", actor: "test", actor_id: "1", workflow: "security.yml", workflow_ref: "Mise-OS/MiseOS-Dev-ID-/.github/workflows/security.yml@refs/heads/main", workflow_sha: "a".repeat(40), run_id: "1", run_number: "1", ref: "refs/heads/main", ref_type: "branch", environment: "prod", iat: NOW - 30, exp: NOW + 300, ...overrides }).setProtectedHeader({ alg: "RS256", kid: "oidc-test" }).sign(oidcPrivateKey.privateKey); }
function digest(v: unknown) { return createHash("sha256").update(canonicalize(v), "utf8").digest("hex"); }
function envelope(manifest: unknown, patch: Partial<SignedEnvelopeV1> = {}) { const u: Omit<SignedEnvelopeV1, "signature"> = { schema: "miseos.signed-envelope/v1", algorithm: "Ed25519", keyId: KEY_ID, payloadDigest: { algorithm: "sha256", value: digest(manifest) }, issuedAt: new Date((NOW - 30) * 1000).toISOString(), expiresAt: new Date((NOW + 300) * 1000).toISOString(), nonce: `${Date.now()}-${Math.random().toString(36).slice(2)}`, audience: AUD, actionId: "action-1", authorizationId: "auth-1", ...patch }; return { ...u, signature: sign(null, envelopeBytes({ ...u, signature: "" }), signingPrivateKey).toString("base64") }; }
function auth(): AuthorizationSnapshot & { requestedOperation: "publish"; resource: string; requestedAt: string } { return { schema: "miseos.authorization/v1", credentialId: "auth-1", subject: SUBJECT, scope: ["publish"], resources: [{ type: "exact", pattern: RESOURCE }], issuedAt: new Date((NOW - 60) * 1000).toISOString(), expiresAt: new Date((NOW + 300) * 1000).toISOString(), state: "SAFE", revocationId: "auth-rev-1", requestedOperation: "publish", resource: RESOURCE, requestedAt: new Date(NOW * 1000).toISOString() }; }
interface S { manifest: unknown; envelope: SignedEnvelopeV1; token: string; authorization: ReturnType<typeof auth>; chain: DelegationCredential[]|null; keyStatus: "valid"|"revoked"|"suspended"|"unknown"; keyOwner: string; revStatus: "valid"|"revoked"|"unknown"; replay: ClaimResult; jwks: URL; }
function base(): S { const manifest = { schema: "miseos.provenance/v1", repository: REPO, commitSha: "a".repeat(40) }; return { manifest, envelope: envelope(manifest), token: "", authorization: auth(), chain: null, keyStatus: "valid", keyOwner: SUBJECT, revStatus: "valid", replay: "claimed", jwks: jwksUrl }; }
function ctx(s: S): VerificationContext { return { keyRegistry: new Keys(s.keyStatus, s.keyOwner), revocationRegistry: new Rev(s.revStatus), replayStore: new Replay(s.replay), expectedAudience: AUD, maxDelegationDepth: 3, maxClockSkewMs: 300_000, oidcToken: s.token, oidcPolicy: { allowedIssuers: ["https://token.actions.githubusercontent.com"], allowedAudiences: [AUD], allowedRepositories: [REPO], allowedRepositoryOwners: ["Mise-OS"], allowedRepositoryIds: ["1338747102"], allowedWorkflows: ["security.yml"], allowedWorkflowRefs: ["Mise-OS/MiseOS-Dev-ID-/.github/workflows/security.yml@refs/heads/main"], allowedWorkflowShas: ["a".repeat(40)], allowedRefs: ["refs/heads/main"], allowedRefTypes: ["branch"], requireEnvironment: "prod", maxClockSkewSeconds: 300, jwksUrl: s.jwks }, trustedIdentityBinding: { githubSubject: SUBJECT, repository: REPO, keyId: KEY_ID } }; }
function badSig(e: SignedEnvelopeV1) { const b = Buffer.from(e.signature, "base64"); b[0] ^= 1; return { ...e, signature: b.toString("base64") }; }
beforeAll(async () => { oidcPrivateKey = generateKeyPairSync("rsa", { modulusLength: 2048 }); oidcJwk = await exportJWK(oidcPrivateKey.publicKey); oidcJwk.kid = "oidc-test"; oidcJwk.alg = "RS256"; oidcJwk.use = "sig"; jwksServer = createServer((req, res) => { if (req.url === "/jwks") { res.setHeader("content-type", "application/json"); res.end(JSON.stringify({ keys: [oidcJwk] })); } else { res.statusCode = 404; res.end(); } }); await new Promise<void>(r => jwksServer.listen(0, "127.0.0.1", r)); const a = jwksServer.address(); if (!a || typeof a === "string") throw new Error("JWKS fixture failed"); jwksUrl = new URL(`http://127.0.0.1:${a.port}/jwks`); const kp = generateKeyPairSync("ed25519"); signingPrivateKey = kp.privateKey; signingPublicDer = kp.publicKey.export({ type: "spki", format: "der" }).toString("base64"); });
afterAll(async () => { await new Promise<void>(r => jwksServer.close(() => r())); });
type Case = { name: string; mutate: (s: S) => Promise<S>|S; allow: boolean };
const cases: Case[] = [
  { name:"01 baseline authorized", mutate:async s=>({...s,token:await oidc()}), allow:true }, { name:"02 wrong subject", mutate:async s=>({...s,token:await oidc({sub:"repo:attacker/repo:ref:refs/heads/main"})}), allow:false }, { name:"03 wrong repository", mutate:async s=>({...s,token:await oidc({repository:"attacker/repo"})}), allow:false }, { name:"04 wrong issuer", mutate:async s=>({...s,token:await oidc({iss:"https://attacker.example"})}), allow:false }, { name:"05 wrong audience", mutate:async s=>({...s,token:await oidc({aud:"https://attacker.example"})}), allow:false }, { name:"06 expired OIDC", mutate:async s=>({...s,token:await oidc({iat:NOW-1000,exp:NOW-10})}), allow:false }, { name:"07 future OIDC", mutate:async s=>({...s,token:await oidc({iat:NOW+1000,exp:NOW+2000})}), allow:false }, { name:"08 workflow ref", mutate:async s=>({...s,token:await oidc({workflow_ref:"Mise-OS/evil/.github/workflows/evil.yml@refs/heads/main"})}), allow:false }, { name:"09 environment", mutate:async s=>({...s,token:await oidc({environment:"dev"})}), allow:false }, { name:"10 repository owner", mutate:async s=>({...s,token:await oidc({repository_owner:"attacker"})}), allow:false },
  { name:"11 unknown key", mutate:s=>({...s,keyStatus:"unknown"}), allow:false }, { name:"12 revoked key", mutate:s=>({...s,keyStatus:"revoked"}), allow:false }, { name:"13 suspended key", mutate:s=>({...s,keyStatus:"suspended"}), allow:false }, { name:"14 wrong envelope key id", mutate:s=>({...s,envelope:{...s.envelope,keyId:"other"}}), allow:false }, { name:"15 key owner mismatch", mutate:s=>({...s,keyOwner:"attacker"}), allow:false }, { name:"16 bad signature", mutate:s=>({...s,envelope:badSig(s.envelope)}), allow:false }, { name:"17 malformed signature", mutate:s=>({...s,envelope:{...s.envelope,signature:"%%%"}}), allow:false }, { name:"18 expired envelope", mutate:s=>({...s,envelope:{...s.envelope,expiresAt:new Date((NOW-10)*1000).toISOString()}}), allow:false }, { name:"19 future envelope", mutate:s=>({...s,envelope:{...s.envelope,issuedAt:new Date((NOW+1000)*1000).toISOString()}}), allow:false }, { name:"20 envelope audience", mutate:s=>({...s,envelope:{...s.envelope,audience:"https://attacker"}}), allow:false },
  { name:"21 manifest mismatch", mutate:s=>({...s,manifest:{tampered:true}}), allow:false }, { name:"22 authorization state", mutate:s=>({...s,authorization:{...s.authorization,state:"REVOKED"}}), allow:false }, { name:"23 authorization subject", mutate:s=>({...s,authorization:{...s.authorization,subject:"attacker"}}), allow:false }, { name:"24 missing operation scope", mutate:s=>({...s,authorization:{...s.authorization,scope:["access"]}}), allow:false }, { name:"25 resource exact mismatch", mutate:s=>({...s,authorization:{...s.authorization,resource:"repo:other:artifact:v1"}}), allow:false }, { name:"26 resource prefix mismatch", mutate:s=>({...s,authorization:{...s.authorization,resources:[{type:"prefix",pattern:"repo:Other"}]}}), allow:false }, { name:"27 resource glob mismatch", mutate:s=>({...s,authorization:{...s.authorization,resources:[{type:"glob",pattern:"repo:Mise-OS/*:release:*"}]}}), allow:false }, { name:"28 authorization expired", mutate:s=>({...s,authorization:{...s.authorization,expiresAt:new Date((NOW-10)*1000).toISOString()}}), allow:false }, { name:"29 authorization future", mutate:s=>({...s,authorization:{...s.authorization,issuedAt:new Date((NOW+1000)*1000).toISOString()}}), allow:false }, { name:"30 revocation unknown", mutate:s=>({...s,revStatus:"unknown"}), allow:false },
  { name:"31 authorization revoked", mutate:s=>({...s,revStatus:"revoked"}), allow:false }, { name:"32 missing authorization revocation id", mutate:s=>({...s,authorization:{...s.authorization,revocationId:undefined}}), allow:false }, { name:"33 required delegation absent", mutate:s=>({...s,envelope:{...s.envelope,delegationId:"deleg-1"}}), allow:false }, { name:"34 unexpected delegation", mutate:s=>({...s,chain:[{} as DelegationCredential]}), allow:false }, { name:"35 delegation invalid root", mutate:s=>({...s,envelope:{...s.envelope,delegationId:"deleg-1"},chain:[{} as DelegationCredential]}), allow:false }, { name:"36 delegation invalid target", mutate:s=>({...s,envelope:{...s.envelope,delegationId:"deleg-1"},chain:[{} as DelegationCredential]}), allow:false }, { name:"37 replayed nonce", mutate:s=>({...s,replay:"replayed"}), allow:false }, { name:"38 replay indeterminate", mutate:s=>({...s,replay:"indeterminate"}), allow:false }, { name:"39 missing expiration", mutate:s=>{const e={...s.envelope}; delete e.expiresAt; return {...s,envelope:e};}, allow:false }, { name:"40 empty nonce", mutate:s=>({...s,envelope:{...s.envelope,nonce:""}}), allow:false },
  { name:"41 wrong payload digest", mutate:s=>({...s,envelope:{...s.envelope,payloadDigest:{algorithm:"sha256",value:"0".repeat(64)}}}), allow:false }, { name:"42 authorization id binding", mutate:s=>({...s,authorization:{...s.authorization,credentialId:"attacker-auth"}}), allow:false }, { name:"43 workflow name", mutate:async s=>({...s,token:await oidc({workflow:"attacker"})}), allow:false }, { name:"44 workflow SHA", mutate:async s=>({...s,token:await oidc({workflow_sha:"b".repeat(40)})}), allow:false }, { name:"45 git ref", mutate:async s=>({...s,token:await oidc({ref:"refs/heads/evil"})}), allow:false }, { name:"46 ref type", mutate:async s=>({...s,token:await oidc({ref_type:"tag"})}), allow:false }, { name:"47 JWKS unavailable", mutate:async s=>({...s,token:await oidc(),jwks:new URL("http://127.0.0.1:1/jwks")}), allow:false }, { name:"48 unknown key remains deny", mutate:s=>({...s,keyStatus:"unknown"}), allow:false }, { name:"49 unknown revocation remains deny", mutate:s=>({...s,revStatus:"unknown"}), allow:false }, { name:"50 replay race loser", mutate:s=>({...s,replay:"replayed"}), allow:false },
];
describe("security RC2 adversarial authority gate", () => { it("contains exactly 50 cases", () => expect(cases).toHaveLength(50)); it.each(cases)("$name", async c => { const s = await c.mutate(base()); if (!s.token) s.token = await oidc(); const d = await verify(s.envelope, s.manifest, s.chain, s.authorization, ctx(s)); expect(authorityDecision(d)).toBe(c.allow ? "allow" : "deny"); if (!c.allow) expect(d.effect).not.toBe("allow"); }); it("release gate: no unauthorized scenario reaches ALLOW", async () => { for (const c of cases.filter(x => !x.allow)) { const s = await c.mutate(base()); if (!s.token) s.token = await oidc(); const d = await verify(s.envelope, s.manifest, s.chain, s.authorization, ctx(s)); expect(authorityDecision(d), c.name).toBe("deny"); } }); });
