- name: Consistent Release
  # You may pin to the exact commit or the version.
  # uses: agilecustoms/release@b39dff0ebe55fd48c706f18d02f8246ea6c1db6c
  uses: agilecustoms/release@v3.0.0
  with:
    # AWS account to publish artifacts to. Not needed if there are no artifacts, just git tag
    aws-account: # optional
    # AWS region
    aws-region: # optional
    # IAM role to assume to publish, e.g., `ci/publisher`
    aws-role: # optional
    # CodeArtifact domain name, e.g., `mycompany`
    aws-codeartifact-domain: # optional
    # CodeArtifact repository name, e.g., `maven`
    aws-codeartifact-repository: # optional
    # Two possible values: build and publish. publish - publish maven artifacts to AWS CodeArtifact, build - just access CodeArtifact to update version in pom.xml
    aws-codeartifact-maven: # optional
    # If true, then push docker image to ECR
    aws-ecr: # optional
    # Required if uploading to S3 (i.e. s3/ directory exists)
    aws-s3-bucket: # optional
    # Allows you to specify S3 bucket directory to upload artifacts to. By default, just place in `bucket/{repo-name}/{version}/*`
    aws-s3-dir: # optional
    # Changelog file path. Pass empty string to disable changelog generation
    changelog-file: # optional, default is CHANGELOG.md
    # Title of the changelog file (first line of the file)
    changelog-title: # optional, default is # Changelog
    # Allows you to enforce branch prefix for dev-releases; this helps to write auto-disposal rules. Empty string disables enforcement
    dev-branch-prefix: # optional, default is feature/
    # Allows you to create a temporary named release, mainly for dev testing. Implementation is different for all supported artifact types
    dev-release: # optional, default is false
    # When the next version to be released is 1.2.4, then also release 1, 1.2, and latest. Not desired for public terraform modules
    floating-tags: # optional, default is true
    # Enabled by default, specify empty string to disable caching
    java-cache: # optional, default is maven
    # see https://github.com/actions/setup-java "cache-dependency-path"
    java-cache-dependency-path: # optional
    # Java distribution, use Temurin as it is pre-cached in ubuntu-latest
    java-distribution: # optional, default is temurin
    # Java version to use
    java-version: # optional, default is 21
    # Node.js version to publish npm packages, default is 22 because it is highest pre-cached in Ubuntu 24 (latest at time of writing)
    node-version: # optional, default is 22
    # Additional semantic-release npm dependencies, needed to use non-default commit analyzer preset
    npm-extra-deps: # optional
    # Used together with env variable `NPM_TOKEN` to publish npm package. Specifies package visibility: public or private
    npm-visibility: # optional, default is public
    # Python version, so far only used to bump version in pyproject.toml
    python-version: # optional, default is 3.13
    # Shell script that allows you to update version in custom file(s), not only files governed by build tool (pom.xml, package.json, etc)
    pre-publish-script: # optional
    # semantic-release "branches" configuration
    release-branches: # optional
    # Repeat `.releaserc.json` `channel` behavior when set `version` explicitly
    release-channel: # optional
    # If true, then create a GitHub release with the same name as the tag
    release-gh: # optional, default is true
    # semantic-release plugins configuration
    release-plugins: # optional
    # Text to print in step summary. Can use `${version}` placeholder. Default is `### Released ${version}`. Set empty string to omit summary generation
    summary: # optional, default is ### Released ${version}
    # By default, the tag (version) has format `v1.0.0`. Use `${version}` to remove `v` prefix
    tag-format: # optional
    # Update version in language-specific manifest files (e.g., pom.xml, package.json, pyproject.toml)
    update-version-in-manifest: # optional, default is true
    # Explicit version to use instead of auto-generation
    version: # optional
    # Allows you to bump a version without semantic commits
    version-bump: # optional
