- name: Consistent Release
  # You may pin to the exact commit or the version.
  # uses: agilecustoms/release@b39dff0ebe55fd48c706f18d02f8246ea6c1db6c
  uses: agilecustoms/release@v3.0.0
  with:
    # Changelog file path. Pass empty string to disable changelog generation
    changelog-file: CHANGELOG.md
    # Title of the changelog file (first line of the file)
    changelog-title: '# Changelog'
    # Allows you to enforce branch prefix for dev-releases; this helps to write auto-disposal rules. Empty string disables enforcement
    dev-branch-prefix: 'feature/'
    # Allows you to create a temporary named release, mainly for dev testing. Implementation is different for all supported artifact types
    dev-release: false
    # When the next version to be released is 1.2.4, then also release 1, 1.2, and latest. Not desired for public terraform modules
    floating-tags: true
    # Java distribution, use Temurin as it is pre-cached in ubuntu-latest
    java-distribution: temurin
    # Java version to use
    java-version: '21'
    # Node.js version to publish npm packages, default is 22 because it is highest pre-cached in Ubuntu 24 (latest at time of writing)
    node-version: '22'
    # Used together with env variable `NPM_TOKEN` to publish npm package. Specifies package visibility: public or private
    npm-visibility: public
    # Python version, so far only used to bump version in pyproject.toml
    python-version: '3.13'
    # If true, then create a GitHub release with the same name as the tag
    release-gh: true
    # Text to print in step summary. Can use `${version}` placeholder. Default is `### Released ${version}`. Set empty string to omit summary generation
    summary: '### Released ${version}'
    # Update version in language-specific manifest files (e.g., pom.xml, package.json, pyproject.toml)
    update-version-in-manifest: true
